# Generated by Django 5.0.7 on 2024-07-13 23:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dress",
            name="image_url",
        ),
        migrations.AddField(
            model_name="dress",
            name="image",
            field=models.ImageField(default="default_image.png", upload_to="dresses/"),
            preserve_default=False,
        ),
    ]
