# Generated by Django 5.0.7 on 2024-07-13 23:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_remove_dress_image_url_dress_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dress",
            name="image",
            field=models.ImageField(default="default_image.png", upload_to="dresses/"),
        ),
    ]
