# Generated by Django 5.0.7 on 2024-07-14 00:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0003_alter_dress_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="dress",
            name="category",
            field=models.CharField(
                choices=[("Men", "Men"), ("Women", "Women"), ("Kids", "Kids")],
                default="Men",
                max_length=10,
            ),
            preserve_default=False,
        ),
    ]
