# Generated by Django 5.0.7 on 2024-07-16 03:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0004_dress_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="dress",
            name="price",
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="dress",
            name="category",
            field=models.CharField(default="Uncategorized", max_length=50),
        ),
    ]
