# Generated by Django 5.0.7 on 2024-07-16 17:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0005_dress_price_alter_dress_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dress",
            name="category",
            field=models.CharField(
                choices=[("Men", "Men"), ("Women", "Women"), ("Kids", "Kids")],
                default="Uncategorized",
                max_length=50,
            ),
        ),
    ]
